name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Use the branch where you push your code

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Lint HTML
    - name: Lint HTML
      run: |
        npm install -g html
